DROP TABLE IF EXISTS ODONTOLOGOS; CREATE TABLE ODONTOLOGOS (ID INT AUTO_INCREMENT PRIMARY KEY, MATRICULA VARCHAR(100) NOT NULL, NOMBRE VARCHAR(100) NOT NULL,APELLIDO VARCHAR(100) NOT NULL );

-- para test --
INSERT INTO ODONTOLOGOS(MATRICULA,NOMBRE, APELLIDO) VALUES ('987456', 'Diana', 'Vargas'),('65497', 'Beatriz', 'Carvajal');


